
var vars = {
  isPaused: false,
  isPauseLoopFunctions: false,
  isMouseActive: false,
  isCutActive: false,
  platformIsInitialized: false,
  isGlobeActive: false,

  globeRadius:100,
  loopFunctions: [],
  mouseCoords: {x:0, y:0},
  localPlanes: [],

  windowSize:{width:0, height:0},

  currentMilestone: null,

  // loaded textures will be stored here.
  textures:[],

  // default paths stored here
  path:{
    textures: '/assets/textures/',
  },

  milestones: [
    {
      id: 0,
      coords:{lat:42.296928, lng:-71.291862},
      city:'Wellesley',
      year: '2011',
      model: '11_The-start.glb',
      title: 'Where it all <$began$>',
      description: 'Founded in 2011 with a focus on mobile technology solutions, Mobiquity continuously adapted in response to client needs and evolving technology.',
      sound: '/vo/VO_Milestone_011.mp3',
      time:9,
    },
    {
      id: 1,
      coords:{lat:47.606209, lng:-122.332069},
      city:'Seattle',
      year: '2011',
      model: '03_AWS.glb',
      title: 'From partnership to <$events$> <$partner$>',
      description: 'Mobiquity has worked with AWS as an APN Premier Consulting Partner since 2011 to deliver 100% cloud-based innovation to its clients, including design & dev of the AWS re:Invent app since 2016.',
      sound: '/vo/VO_Milestone_003.mp3',
      time:15,
    },
    {
      id: 2,
      coords:{lat:38.63028, lng:-90.20031},
      city:'St Louis, MO',
      year: '2012',
      model: '01_Self-service-kiosk.glb',
      title: 'Panera self-service kiosks',
      description: 'Panera wanted to set the new digital standard for quick service restaurants. Mobiquity helped them create an omnichannel eCommerce platform and introduced self-service kiosks & mobile ordering.',
      sound: '/vo/VO_Milestone_001.mp3',
      time:11,
    },
    {
      id: 3,
      coords:{lat:23.022505, lng:72.571365},
      city:'Ahmedabad',
      year: '2015',
      model: '12_Expansion-overseas.glb',
      title: 'Going <$global$>',
      description: 'With the acquisitions of Xaton and Morgan Clark, Mobiquity extended its operations into Europe & India.',
      sound: '/vo/VO_Milestone_012.mp3',
      time:6,
    },
    {
      id: 4,
      coords:{lat:50.850346, lng:4.351721},
      city:'Amsterdam',
      year: '2016',
      model: '05_Cloud-based-protection.glb',
      title: 'Cloud-based fraud <$protection$>',
      description: 'Surepay introduced an IBAN name check to fight fraudulent payment transactions in the Netherlands with an AWS cloud-based mobile solution built using Mobiquity’s Digital Traction Model.',
      sound: '/vo/VO_Milestone_005.mp3',
      time:10,
    },
    {
      id: 5,
      coords:{lat:37.774929, lng:-122.419418},
      city:'San Francisco',
      year: '2017',
      model: '02_World_s-first-digital-pill.glb',
      title: 'Patient health goes <$digital$>',
      description: 'Otsuka worked with Mobiquity to design and develop a breakthrough drug-device combination product. Its new data on drug consumption helps patients, caregivers & families stay informed.',
      sound: '/vo/VO_Milestone_002.mp3',
      time: 11,
    },
    {
      id: 6,
      coords:{lat:52.344718, lng:9.799318},
      city:'Amsterdam',
      year: '2018',
      model: '06_Digital-Traction.glb',
      title: 'Accelerating Innovation with <$Digtial$> <$Traction$>',
      description: 'A large European bank establishes an innovation factory with Mobiquity, using its Digital Traction Model, that has since worked on 15+ value propositions over the course of 3 years.',
      sound: '/vo/VO_Milestone_006.mp3',
      time:11,
    },
    {
      id: 7,
      coords:{lat:14.604847, lng:120.77997},
      city:'Manila',
      year: '2018',
      model: '08_BPI.glb',
      title: 'A <$Better$> Digital Banking Experience',
      description: 'BPI engaged Mobiquity to go live with an online portal and mobile banking offering. BPI Online has hit the 4 million+ mark for enrolled users, and it experienced a transaction surge of 87% in 2019.',
      sound: '/vo/VO_Milestone_008.mp3',
      time:14,
    },
    {
      id: 8,
      coords:{lat:35.794325, lng:-78.642417},
      city:'North Carolina',
      year: '2018',
      model: '09_Alexa.glb',
      title: '<$Talking$> Turkey in the kitchen',
      description: 'Butterball worked with Mobiquity to design and launch a multi-modal Amazon Alexa skill that provides a voice channel for US consumers to find answers to their most common turkey topics.',
      sound: '/vo/VO_Milestone_009.mp3',
      time:10,
    },
    {
      id: 9,
      coords:{lat:-13.545140, lng:-58.819939},
      city:'Latin America',
      year: '2018',
      model: '10_Secure-Scalalble-Payments.glb',
      title: 'Secure, Scalable Payments Gateway',
      description: 'To ensure scalable access to data services & micropayment processing for 30M+ users, a large LatAm telecom worked with Mobiquity to create a digital engagement platform & payment gateway.',
      sound: '/vo/VO_Milestone_010.mp3',
      time:11,
    },
    {
      id: 10,
      coords:{lat:26.0667001, lng:50.557701},
      city:'Manama',
      year: '2019',
      model: '04_ILA.glb',
      title: 'Launch of <$ila$> <$Bank$>',
      description: 'Bank ABC partnered with Mobiquity from strategy & idea inception through to implementation & the launch of Ila Bank; the first digital, mobile-only bank in Bahrain.',
      sound: '/vo/VO_Milestone_004.mp3',
      time:10,
    },
    {
      id: 11,
      coords:{lat:19.039624, lng:72.988701},
      city:'Mumbai',
      year: '2019',
      model: '13_500-employees.glb',
      title: '500 employees',
      description: 'Celebrations across the offices marked the significance of Mobiquity\'s 500th employee.',
      sound: '/vo/VO_Milestone_013.mp3',
      time:5,
    },
    {
      id: 12,
      coords:{lat:13.08268, lng:80.270721},
      city:'Chennai',
      year: '2019',
      model: '15_Hexaware.glb',
      title: 'Hello, <$Hexaware$>',
      description: 'In 2019, Mobiquity is acquired by Hexaware Technologies to accelerate the IT engineering services firm\'s offering around customer experience transformation.',
      sound: '/vo/VO_Milestone_015.mp3',
      time:10,
    },
    {
      id: 13,
      coords:{lat:41.203323, lng:-77.194527},
      city:'Pennsylvania',
      year: '2020',
      model: '07_Wawa.glb',
      title: 'Taking convenience to the <$next$> <$level$>',
      description: 'A customer since 2013, Wawa worked with Mobiquity to deliver improved convenience during the covid pandemic by rolling out additional mobile app features, like curbside & in-app delivery.',
      sound: '/vo/VO_Milestone_007.mp3',
      time:11,
    },
    {
      id: 14,
      coords:{lat:-26.204103, lng:28.047304},
      city:'Johannesburg',
      year: '2020',
      model: '18_1000-employees.glb',
      title: '1000 employees',
      description: 'With the addition of Hexaware Interactive folks to the Mobiquity team, we cross the 1,000 people mark.',
      sound: '/vo/VO_Milestone_018.mp3',
      time: 6,
    },
    {
      id: 15,
      coords:{lat:49.838994, lng:8.691392},
      city:'Amsterdam',
      year: '2021',
      model: '14_Mobster-Award.glb',
      title: 'We celebrate <$Mobstars!$>',
      description: 'From Mobstar awards to Digital First Awards, Mobiquity celebrates and thanks our colleages for their contributions to our clients and our communities.',
      sound: '/vo/VO_Milestone_014.mp3',
      time:8,
    },
    {
      id: 16,
      coords:{lat:-33.860097, lng:151.222226},
      city:'Sydney',
      year: '2021',
      model: '16_Setting-foot-outback.glb',
      title: 'Setting foot in the outback',
      description: 'Mobiquity hires its first employee in Australia in 2021, marking its expanision into the region.',
      sound: '/vo/VO_Milestone_016.mp3',
      time:7,
    },
    {
      id: 17,
      coords:{lat:39.830555, lng:-75.111105},
      city:'Philadelphia',
      year: '2021',
      model: '17_Awards.glb',
      title: 'And the <$award$> goes to...',
      description: 'From Top Consulting Firm to diversity inclusion awards, partner awards and analyst recognitions, the word gets out that Mobiquity is a great place to work.',
      sound: '/vo/VO_Milestone_017.mp3',
      time:10,
    },
    {
      id: 18,
      coords:{lat:18.232057, lng:74.017494},
      city:'Pune',
      year: '2021',
      model: '19_India.glb',
      title: 'We keep expanding in <$India$>',
      description: 'In 2021, Mobiquity opens its third location in India and announces plans to double its footprint in the country. We now have offices in Ahmedabad, Pune and Hyderabad.',
      sound: '/vo/VO_Milestone_019.mp3',
      time:11,
    },
    {
      id: 19,
      //coords:{lat:40.779371, lng:-74.064078}, New york
      //coords:{lat:-33.924870, lng:18.424055}, Cape town
      coords:{lat:53.339561, lng:-2.958824},
      city:'London',
      year: '2021',
      model: '20_Next-frontiers.glb',
      title: 'The next <$frontier$>',
      description: 'Mobiquity marks its 10 year anniversary with a renewed focus on digital products and sets course to help brands achieve brand gravity in the digital space.',
      sound: '/vo/VO_Milestone_020.mp3',
      time:10,
    },
  ],

}

export default vars;
